### PR TITLE
Added operator tuple element label

### LINKED ISSUE #3: Tuple members must all have names or all not have names
According to TS docs it's not allowed to use a variation of labeled and unlabeled tuples. However this is the case for the type declaration of the function [`calc()` in index.d.ts](https://github.com/NickLJudy/numeral-calc/blob/main/src/index.d.ts#L15-L20)

Please consider to either name all the tuple elements or none. The current implementation causes a compile error.

```
numeral-calc/src/index.d.ts:18:5 - error TS5084: Tuple members must all have names or all not have names.

18     '+' | 'and' | 'plus' | 'add' | '-' | 'minus' | 'sub' | 'subtract' | '*' | 'x' | 'multi' | 'multiply' | '/' | 'divide'
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Reference to the documentation:**

 - [Labeled Tuple Elements](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements)

### PR DESCRIPTION
**Pull request by luukvhoudt**
fixes #3

### CODE REVIEW

**Comment by luukvhoudt** [comment]
Please consider merging this PR.

Thank you.

**Comment by heliosnaut** [comment]
@luukvhoudt
 Sorry, I haven't logged in Github recently. It has been merged, if this negligence doesn't cause the loss of functions, I will release the next small version.

**Comment by luukvhoudt** [comment]
Thank you very much!

Please let me know when the npm package will be updated (or if it won't be updated).

**Comment by heliosnaut** [comment]
It could be a couple of days, man,

Are you using this plugin? Do you have any good suggestions or comments to give me back? I would appreciate it.

**Comment by luukvhoudt** [comment]
> It could be a couple of days, man,

Aah it's okay I will use my fork in the meanwhile.

> Are you using this plugin?

Yes in quite a big project, will be deployed later this week.

> Do you have any good suggestions or comments to give me back?

Not at the moment, maybe add some performance/stress tests?

**Comment by heliosnaut** [comment]
Hi @luukvhoudt 
Has been released (v1.0.8) .

**Pull request merged**
